### ISSUE TITLE
Script arguments do not work?

### ISSUE THREAD

**Issue by douglasg14b** [XReelZ/TaledensInvManagerUpdatedUnofficial#7]
I'm trying to change the prefix, so different ships have different prefixes, but it does not appear to work.

I've tried:

- prefix=TIM_MINER
- "prefix=TIM_MINER"
- prefix="TIM_MINER"

![image](https://user-images.githubusercontent.com/1400380/157569069-f0a255c0-cd95-4727-ad53-6443a205689e.png)

**Comment by XReelZ** [comment]
I have checked the issue, it seems that there are some changes in the SE Core or maybe TIM was intended to work with other field than "argument", but the field that should be used for arguments is "Custom Data". In that field you can put multiple arguments on separate rows.
The guide is kind of misleading so I posted it with minor edit.

![image](https://user-images.githubusercontent.com/6606603/157621814-8b891a81-6a81-471b-ac2a-3e8cc9d7288c.png)
![image](https://user-images.githubusercontent.com/6606603/157621936-400faeaa-1579-4388-a9cd-536bc571532c.png)
![image](https://user-images.githubusercontent.com/6606603/157621996-7998d986-42ee-438d-8740-defb256753f3.png)

**Comment by XReelZ** [comment]
Script Arguments
Several of TIM's functions may be configured using script arguments, which should usually be entered into the Custom Data field on the Programmable Block where TIM is installed, but may also be set on (for example) the Timer Block slot which runs TIM's Programmable Block. Multiple arguments may be combined by separating them with spaces.
cycle=#
Sets the cycle length to #, which must be a positive integer. TIM will distribute its workload over this many script executions (up to 11) in order to avoid the script complexity limitation. Default: "cycle=1"
rewrite
Enables tag re-writing. This is the default setting, so this argument does nothing unless you've changed the default in the Advanced Configuration section of the script code.
norewrite
Disables tag re-writing. Recommended only when testing TIM as a replacement for the Automated Inventory Sorting mod, so that your tags remain intact in case you decide to switch back.
tags=AB
Sets the tag open- and close-delimiters to "A" and "B", respectively, which must be different characters. Default: "tags=[]"
prefix=PFX
Sets the tag prefix to "PFX". TIM will ignore tags which have the correct delimiters but do not begin with this text, in order to avoid confusion with other scripts and mods that use tags in block names. Default: "prefix=TIM"
scan=type
Enables scanning blocks of the specified type, which must be "Collectors", "Drills", "Grinders" or "Welders"; this argument may be repeated with additional values. These block types are normally ignored to save time, since they are often used in great numbers and their default conveyor behavior pushes all contents elsewhere anyway. Default: none
quota=mode
Sets the dynamic quota mode, which must be "stable" or "literal". The new default mode is "stable", in which percentage quotas are applied against a theoretical item type total which is derived from the median of the current subtype inventory ratios. The original "literal" behavior applies percentage quotas to the true item type total, but this can cause the effective quotas to become a confusing moving target in the case when a few items are produced or salvaged in large amounts.
debug=type
Enables detailed debugging of specific subroutines, which can be "quotas", "sorting", "refineries" or "assemblers". This can help to diagnose problems with these parts of the script logic, especially when other mods are involved.

**Comment by douglasg14b** [comment]
Thanks!
